### ISSUE TITLE
pymesh.test() is not passed

### ISSUE THREAD

**Issue by JimmyJune** [qnzhou/PyMesh#64]
after I run : docker build .
and run pymesh.test()
I got this：
............................................................/usr/local/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
...F.....................................................................
======================================================================
FAIL: test_stiffness_matrix (test_assembler.AssemblerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pymesh2-0.1.14-py3.6-linux-x86_64.egg/pymesh/tests/test_assembler.py", line 59, in test_stiffness_matrix
    self.assert_PSD(K);
  File "/usr/local/lib/python3.6/site-packages/pymesh2-0.1.14-py3.6-linux-x86_64.egg/pymesh/tests/test_assembler.py", line 31, in assert_PSD
    self.assertLessEqual(0.0, eig_values[0]);
AssertionError: 0.0 not less than or equal to -2.217760325658809e-18

----------------------------------------------------------------------
Ran 133 tests in 2.925s

FAILED (failures=1)
<nose.result.TextTestResult run=133 errors=0 failures=1>

how could I  fixed this?

**Comment by qnzhou** [comment]
I have pushed a fix.  Can you `git pull` and try running the unit tests again?  Thanks!

**Comment by JimmyJune** [comment]
i run 
git pull
and build again.
still get some error:
[ 64%] Building CXX object tools/Tetrahedralization/CMakeFiles/lib_tetrahedralization.dir/TetrahedralizationEngine.cpp.o
tools/Tetrahedralization/CMakeFiles/lib_tetrahedralization.dir/build.make:62: recipe for target 'tools/Tetrahedralization/CMakeFiles/lib_tetrahedralization.dir/TetrahedralizationEngine.cpp.o' failed
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[2]: *** [tools/Tetrahedralization/CMakeFiles/lib_tetrahedralization.dir/TetrahedralizationEngine.cpp.o] Error 4
make[1]: *** [tools/Tetrahedralization/CMakeFiles/lib_tetrahedralization.dir/all] Error 2
CMakeFiles/Makefile2:1906: recipe for target 'tools/Tetrahedralization/CMakeFiles/lib_tetrahedralization.dir/all' failed
make: *** [all] Error 2
Makefile:83: recipe for target 'all' failed
Traceback (most recent call last):
  File "./setup.py", line 158, in <module>
    distclass=BinaryDistribution,
  File "/usr/local/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "./setup.py", line 79, in run
    self.build_pymesh();
  File "./setup.py", line 73, in build_pymesh
    check_call(command.split());
  File "/usr/local/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2.
The command '/bin/sh -c ./setup.py build && ./setup.py install && rm -rf build third_party/build' returned a non-zero code: 1
